Php 62
Abdujilil/PHPTravels pull request #33
Opened 2021-02-04 19:59 UTC by zulhumar717

2021-02-04 20:45 UTC, Abdujilil requested changes
LoginPageTest line 25, expected URL after user logged in is supposed to be "https://www.phptravels.net/account/".

2021-02-04 21:03 UTC, Atilla1227 requested changes
Please resolve the conflicts

2021-02-05 00:58 UTC, Abdujilil approved these changes

2021-02-05 01:07 UTC, Atilla1227 approved these changes

2021-02-05 01:08 UTC, merged